# Generated by Django 5.1.6 on 2025-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_industry', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=100)),
                ('business_model', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('market_segment', models.CharField(max_length=100)),
            ],
        ),
    ]
