# Generated by Django 5.1.6 on 2025-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='focus',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industrymapping',
            name='industry_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
