# Generated by Django 5.1.6 on 2025-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userselection_focus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainIndustry',
            new_name='main_industry',
        ),
        migrations.AlterField(
            model_name='industrymapping',
            name='industry_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='industrymapping',
            table='industry_mapping',
        ),
        migrations.AlterModelTable(
            name='main_industry',
            table='main_industry',
        ),
        migrations.AlterModelTable(
            name='userselection',
            table='user_selection',
        ),
    ]
