# Generated by Django 5.1.6 on 2025-04-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_mainindustry_main_industry_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustryMapping',
            new_name='industry_mapping',
        ),
    ]
