# Generated by Django 5.1.6 on 2025-04-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_industrymapping_industry_mapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSelection',
            new_name='user_selection',
        ),
    ]
